apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: node-api-v4
          image: xridhar/node-api-v4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
